# Generated by Django 4.0.5 on 2022-06-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVTApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='FechDeNac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
